In [1]:
import pandas as pd
import numpy as np
import h2o
from h2o.estimators import H2OGradientBoostingEstimator
from h2o.estimators import H2OXGBoostEstimator
from h2o.grid.grid_search import H2OGridSearch
from sklearn.metrics import confusion_matrix, f1_score, precision_recall_curve, auc

In [2]:
h2o.init(port=12345)

Checking whether there is an H2O instance running at http://localhost:12345. connected.


--------------------------  -------------------------------------
H2O_cluster_uptime:         4 mins 35 secs
H2O_cluster_timezone:       America/Sao_Paulo
H2O_data_parsing_timezone:  UTC
H2O_cluster_version:        3.46.0.6
H2O_cluster_version_age:    1 month and 4 days
H2O_cluster_name:           H2O_from_python_lucasmalheiros_230ljg
H2O_cluster_total_nodes:    1
H2O_cluster_free_memory:    1.556 Gb
H2O_cluster_total_cores:    8
H2O_cluster_allowed_cores:  8
H2O_cluster_status:         locked, healthy
H2O_connection_url:         http://localhost:12345
H2O_connection_proxy:       {"http": null, "https": null}
H2O_internal_security:      False
Python_version:             3.12.3 final
--------------------------  -------------------------------------

In [3]:
def convert_to_h2o_frame(data: pd.DataFrame) -> h2o.H2OFrame:
    """Converte um pd.DataFrame em um h2o.H2OFrame"""
    print('Performing conversion from pd.DataFrame to h2o.H2OFrame...')
    # Colunas de datas
    cols_to_date = [col for col in data.dtypes[data.dtypes == 'datetime64[ns]'].index]
    # Colunas a converter para categórica
    cols_to_factor = [col for col in data.dtypes[(data.dtypes == 'object') | (data.dtypes == 'category')].index]
    # Colunas a converter a numeric
    cols_numerics = [col for col in data.dtypes[(data.dtypes != 'object') & (data.dtypes != 'category') & (data.dtypes != 'datetime64[ns]')].index]
    # Adicionar os tipos de colunas ao dicionário col_dtypes
    col_dtypes = {}
    for col in cols_to_date:
        col_dtypes[col] = 'time'
    for col in cols_to_factor:
        col_dtypes[col] = 'enum'
    for col in cols_numerics:
        col_dtypes[col] = 'numeric'
    # Converte a h2o
    data = h2o.H2OFrame(data, column_types=col_dtypes, na_strings=['NA', 'none', 'None', 'nan', 'NaN', '<NA>'])
    print('Successful conversion from pd.DataFrame to h2o.H2OFrame.')
    return data

# Data preparation

In [4]:
# Resultados
df_resultados = pd.read_csv('resultados_instancias_tcc.csv')
df_resultados = df_resultados[['Instancias'] + [col for col in df_resultados.columns if col.startswith('Obj_') or col.startswith('Time_')]]
df_resultados = df_resultados[df_resultados['Obj_RF_T_0'] != np.inf]  # Remove infactíveis

In [5]:
# Features criadas de create_features_dataset.py
df_features = pd.read_csv('multi_plant_instance_features.csv')

In [6]:
df = df_features.merge(df_resultados, left_on='instance', right_on='Instancias', how='inner').drop(columns=['Instancias', 'instance'])

In [7]:
df.head(3)

num_products  num_plants  num_periods  binary_vars  total_demand  \
0           120           2           12         2880        263136   
1            60          20           12        14400       1305703   
2           120           6           12         8640        788211   

   avg_demand_per_product  variance_demand_per_product  \
0               91.366667                  2807.950972   
1               90.673819                  2699.046453   
2               91.228125                  2765.053630   

   std_demand_per_product  mean_utilization  max_utilization  ...  Obj_RF_4_2  \
0               52.990103          1.000118         1.067356  ...         NaN   
1               51.952348          1.000154         1.143479  ...         NaN   
2               52.583777          0.999516         1.092181  ...         NaN   

   Time_RF_4_2  Obj_RF_4_3  Time_RF_4_3  Obj_RF_6_0  Time_RF_6_0  Obj_RF_6_1  \
0          NaN         NaN          NaN   829221.10      1800.13   811118.49   
1          NaN         NaN          NaN  2404264.97      1069.06  2404219.27   
2          NaN         NaN          NaN  2000140.81      1800.32  1991086.02   

   Time_RF_6_1  Obj_RF_T_0  Time_RF_T_0  
0      1200.63   809910.65       1800.1  
1      1018.31  2404240.72        952.5  
2      1214.94  2106419.81       1800.2  

[3 rows x 79 columns]

# Construção de targets

In [8]:
obj_columns = [col for col in df.columns if col.startswith('Obj_')]
time_columns = [col for col in df.columns if col.startswith('Time_')]

## Target em função objetivo (BEST)

In [9]:
# Seleciona para cada instância o método com menor função objetivo para a coluna BEST
df['BEST'] = df[obj_columns].idxmin(axis=1)
df['BEST'] = df['BEST'].str.replace('Obj_', '')

In [10]:
df['BEST'].value_counts()

BEST
RF_T_0    221
RF_6_0     73
RF_3_1     60
RF_2_0     52
RF_1_0     48
RF_6_1     45
RF_2_1     36
RF_3_0     33
RF_4_0     30
Name: count, dtype: int64

## Target com compromisso de tempo (BEST_TIME)

In [11]:
for obj_col, time_col in zip(obj_columns, time_columns):
    df[f'Adjusted_{obj_col}'] = (
        df[obj_col] * np.maximum(np.log(df[time_col]) / np.log(1000), 1)
    )
adjusted_columns = [col for col in df.columns if col.startswith('Adjusted_')]

In [12]:
# Seleciona para cada instância o método com menor função objetivo para a coluna BEST
df['BEST_TIME'] = df[adjusted_columns].idxmin(axis=1)
df['BEST_TIME'] = df['BEST_TIME'].str.replace('Adjusted_Obj_', '')

In [13]:
df['BEST_TIME'].value_counts()

BEST_TIME
RF_T_0    119
RF_1_0    115
RF_3_1     72
RF_6_0     72
RF_6_1     69
RF_2_0     58
RF_2_1     35
RF_3_0     30
RF_4_0     28
Name: count, dtype: int64

# Preprocessamento de dados

## Drop Obj_ e Time_

In [14]:
df = df.drop(columns=obj_columns + time_columns + adjusted_columns)

In [15]:
# Embaralhar dataset
df = df.sample(frac=1)

In [16]:
# Transformar em classificação binária
df['BEST'] = df['BEST'].apply(lambda x: 'Gurobi' if x == 'RF_T_0' else 'RF')
df['BEST_TIME'] = df['BEST_TIME'].apply(lambda x: 'Gurobi' if x == 'RF_T_0' else 'RF')

## Convert para H2O frame

In [17]:
# Conversão para H2O frame
hf = convert_to_h2o_frame(df)

Performing conversion from pd.DataFrame to h2o.H2OFrame...
Parse progress: |████████████████████████████████████████████████████████████████| (done) 100%
Successful conversion from pd.DataFrame to h2o.H2OFrame.


In [18]:
# # Train test split
hf_train, hf_test = hf.split_frame(ratios=[.8], seed=2112)

# Treino (GBM)

In [19]:
target = 'BEST_TIME'
predictors = [c for c in hf_train.columns if c not in ['BEST', 'BEST_TIME']]

In [20]:
gbm_model = H2OGradientBoostingEstimator(
    nfolds=20,
    keep_cross_validation_predictions=True,
    seed=2112,
    stopping_rounds=10,
    stopping_metric="AUTO",
    stopping_tolerance=0.001,
    balance_classes=False
)

In [21]:
xgboost_model = H2OXGBoostEstimator(booster='dart',
                                    normalize_type="tree",
                                    seed=2112,
                                    nfolds=10,
                                    keep_cross_validation_predictions=True)

In [22]:
# # Hiper Parâmetros
# hyper_params = {
#     "learn_rate": list(
#         np.round(np.arange(0.01, 0.1, 0.01), 3)
#     ),  # Narrowed range for learning rate list(np.round(np.arange(0.05, 0.3, 0.05), 3)),
#     "max_depth": list(
#         np.arange(5, 10, 1)
#     ),  # Reduced maximum depth list(np.arange(5, 15, 1)),
#     "ntrees": list(
#         np.arange(50, 150, 20)
#     ),  # Increased number of trees list(np.arange(20, 70, 10)),
#     "sample_rate": list(
#         np.round(np.arange(0.5, 0.9, 0.1), 3)
#     ),  # Adjusted sample rate range list(np.round(np.arange(0.5, 1.0, 0.1), 3)),
#     "col_sample_rate": list(
#         np.round(np.arange(0.5, 1.0, 0.1), 3)
#     ),  # Slightly adjusted col sample rate range list(np.round(np.arange(0.3, 1.0, 0.1), 3)),
# }
# # Tipo de pesquisa da grid. Em caso de RandomDiscrete, corre até max_models(n modelos)
# search_criteria = {
#     "strategy": "RandomDiscrete",
#     "max_models": 10,
#     # "max_runtime_secs": 180,
#     "seed": 1
# }

In [23]:
# # Construir grid com parâmetros e critérios de procura de melhor modelo
# grid = H2OGridSearch(model=gbm_model, 
#                      search_criteria=search_criteria, 
#                      hyper_params=hyper_params)
# # Treinar grid
# grid.train(x=predictors, y=target, training_frame=hf_train);

In [24]:
# gbm_grid = grid.get_grid(sort_by="rmse", decreasing=False)
# model = gbm_grid.models[0]

In [25]:
model = xgboost_model
model.train(x=predictors, y=target, training_frame=hf_train);

xgboost Model Build progress: |

/home/lucasmalheiros/Documents/Pesquisa Operacional/tcc-relax-and-fix/venv/lib/python3.12/site-packages/h2o/estimators/estimator_base.py:192: RuntimeWarning: Dropping bad and constant columns: [num_periods]
  warnings.warn(mesg["message"], RuntimeWarning)


██████████████████████████████████████████████████| (done) 100%


# Avaliação das métricas de treino

In [26]:
# Variáveis mais importantes na escolha
importancia_var = model.varimp(use_pandas=True)
importancia_var

variable  relative_importance  scaled_importance  \
0               variance_setup_cost           103.330269           1.000000   
1                    avg_setup_cost           100.630486           0.973872   
2                   max_utilization            84.489868           0.817668   
3          skew_transportation_cost            81.229973           0.786120   
4          kurt_transportation_cost            79.049362           0.765017   
5          demand_to_capacity_ratio            56.236767           0.544243   
6                   std_utilization            51.615456           0.499519   
7    demand_to_capacity_interaction            39.473785           0.382016   
8                  mean_utilization            20.726967           0.200589   
9                   min_utilization            18.815672           0.182093   
10            time_per_unit_of_cost            18.429834           0.178359   
11        total_transportation_cost            17.203362           0.166489   
12                       p75_demand            12.678864           0.122702   
13                 kurt_utilization            11.111150           0.107530   
14                 skew_utilization            11.049004           0.106929   
15       demand_to_cost_interaction            10.904472           0.105530   
16                    skew_capacity            10.281030           0.099497   
17                  skew_setup_time             9.978977           0.096574   
18                    kurt_capacity             9.656144           0.093449   
19             skew_production_time             8.482681           0.082093   
20                  kurt_setup_cost             8.421843           0.081504   
21                      kurt_demand             7.955684           0.076993   
22              avg_production_cost             7.723490           0.074746   
23                      binary_vars             7.527840           0.072852   
24         variance_production_cost             7.005980           0.067802   
25               avg_inventory_cost             6.557173           0.063458   
26   setup_to_production_time_ratio             6.538216           0.063275   
27   avg_demand_to_setup_cost_ratio             5.827806           0.056400   
28                      skew_demand             5.144487           0.049787   
29          variance_inventory_cost             4.940950           0.047817   
30                  skew_setup_cost             4.719308           0.045672   
31             kurt_production_cost             4.656025           0.045060   
32  capacity_utilization_efficiency             3.589540           0.034739   
33           avg_demand_per_product             3.458046           0.033466   
34                        cv_demand             3.208974           0.031056   
35      variance_demand_per_product             2.332348           0.022572   
36                       iqr_demand             1.703544           0.016486   
37             kurt_production_time             1.671093           0.016172   
38   setup_to_production_cost_ratio             1.245553           0.012054   
39                     num_products             0.987001           0.009552   
40                     total_demand             0.971157           0.009399   
41             skew_production_cost             0.932485           0.009024   
42                       p25_demand             0.792609           0.007671   
43                  kurt_setup_time             0.590537           0.005715   
44              kurt_inventory_cost             0.578904           0.005602   

    percentage  
0     0.120931  
1     0.117772  
2     0.098882  
3     0.095066  
4     0.092514  
5     0.065816  
6     0.060407  
7     0.046198  
8     0.024258  
9     0.022021  
10    0.021569  
11    0.020134  
12    0.014839  
13    0.013004  
14    0.012931  
15    0.012762  
16    0.012032  
17    0.011679  
18    0.011301  
19    0.009928  
20    0.009856  
21    0.009311  
2

In [28]:
# model.partial_plot(frame=hf_train, cols=['total_transportation_cost'], figsize=(5, 5), targets=['RF_T_0', 'RF_1_0']);

In [29]:
# Previsões
actual = hf_train[target].as_data_frame(use_multi_thread=True)[target]
predictions = model.cross_validation_holdout_predictions()
predict = predictions[0].as_data_frame(use_multi_thread=True)['predict']

/home/lucasmalheiros/Documents/Pesquisa Operacional/tcc-relax-and-fix/venv/lib/python3.12/site-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"
/home/lucasmalheiros/Documents/Pesquisa Operacional/tcc-relax-and-fix/venv/lib/python3.12/site-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"


In [30]:
# Confusion matrix
cm = confusion_matrix(actual, predict)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[ 76  25]
 [ 15 375]]


In [ ]:
# Olhar recall

In [31]:
# Precisão
cm.trace() / cm.sum()

np.float64(0.9185336048879837)

In [32]:
# F1 score
f1 = f1_score(actual, predict, average='weighted')
print(f'\nF1 Score: {f1:.4f}')


F1 Score: 0.9169


# Avaliação no dataset de teste

In [ ]:
# Previsões sobre teste
actual_test = hf_test[target].as_data_frame(use_multi_thread=True)[target]
predictions_test = model.predict(hf_test)
predict_test = predictions_test[0].as_data_frame(use_multi_thread=True)['predict']

xgboost prediction progress: |

/home/lucasmalheiros/Documents/Pesquisa Operacional/tcc-relax-and-fix/venv/lib/python3.12/site-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"


███████████████████████████████████████████████████| (done) 100%


/home/lucasmalheiros/Documents/Pesquisa Operacional/tcc-relax-and-fix/venv/lib/python3.12/site-packages/h2o/frame.py:1983: H2ODependencyWarning: Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using multi-thread, install polars and pyarrow and use it as pandas_df = h2o_df.as_data_frame(use_multi_thread=True)

  warnings.warn("Converting H2O frame to pandas dataframe using single-thread.  For faster conversion using"


In [ ]:
# Confusion matrix
cm = confusion_matrix(actual_test, predict_test)
print("Confusion Matrix:\n", cm)

Confusion Matrix:
 [[16  1  0  1  0  1  0  0  0]
 [ 0  3  1  3  1  1  1  0  0]
 [ 0  0  5  0  0  0  0  1  0]
 [ 2  1  0  1  0  0  1  0  0]
 [ 0  1  0  2  9  0  0  2  1]
 [ 0  0  0  1  3  1  1  1  0]
 [ 0  0  0  1  0  0  3  4  3]
 [ 0  0  0  0  3  0  3  7  0]
 [ 0  0  0  0  0  1  3  1 16]]


In [ ]:
# Precisão
cm.trace() / cm.sum()

np.float64(0.5700934579439252)

In [ ]:
# F1 score
f1 = f1_score(actual_test, predict_test, average='weighted')
print(f'\nF1 Score: {f1:.4f}')


F1 Score: 0.5740
